### ISSUE TITLE
Does not work with Rails 6

### ISSUE THREAD

**Issue by ELepolt** [tma1/dossier#76]
Start up a new rails app 

```
# Note: Not exact

rails _6.0.0.0_ new rails6

# Add dossier to gemfile
bundle install
rails generate scaffold Post name:string title:string content:text

rails c
Post.all
```
The final command spits out an error: `ArgumentError (wrong number of arguments (given 2, expected 1))`

Here's a working repo to reproduce the issue. You can swap between rails 6 and rails 5 to see that it is working in 5.
https://github.com/ELepolt/rails6-dossier

**Comment by n00dle** [comment]
The underlying issue is that `dossier` depends on the `arel` gem, but that gem has become part of ActiveRecord. When AR tries to run, it picks up the separate `arel` gem. The two `arel` versions have diverged to the point of incompatibility, resulting in the `ArgumentError`. The stacktrace looks something like this:

```
ArgumentError: wrong number of arguments (given 2, expected 1)
... gemdir/arel-9.0.0/lib/arel/visitors/to_sql.rb:73:in `compile'
... gemdir/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:35:in `to_sql_and_binds'
```
